### ISSUE TITLE
/home/pvelesko/t/chip-spv/bitcode/devicelib.cl:822:10: error: use of undeclared identifier 'sub_group_ballot'   return sub_group_ballot(predicate).x;

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/chip-spv#337]

**Comment by pvelesko** [comment]
Introduced in 62b1915991a7503a96c8bcefd0dc4cdc5346bcd3

**Comment by pvelesko** [comment]
I can't reproduce this on CI machine but I can reproduce it on JLSE.
